version: '3.8'

services:
  api:
    build: ./api
    container_name: pulse-api
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: pulse-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pulse
      MYSQL_USER: pulse
      MYSQL_PASSWORD: pulsepass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pulse-frontend
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - api


volumes:
  db_data:
